// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert, DispatchError, ERRORS } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null
    this._handler5 = null
    this._handler6 = null
    this._handler7 = null
    this._handler8 = null
    this._handler9 = null
    this._handler10 = null
    this._handler11 = null

    this._missing = 12
  }

  add (name, handler) {
    switch (name) {
      case '@tamarind/add-writer':
        this._handler0 = handler
        break
      case '@tamarind/add-invite':
        this._handler1 = handler
        break
      case '@tamarind/add-board':
        this._handler2 = handler
        break
      case '@tamarind/rename-board':
        this._handler3 = handler
        break
      case '@tamarind/delete-board':
        this._handler4 = handler
        break
      case '@tamarind/add-item':
        this._handler5 = handler
        break
      case '@tamarind/add-items':
        this._handler6 = handler
        break
      case '@tamarind/update-item':
        this._handler7 = handler
        break
      case '@tamarind/reorder':
        this._handler8 = handler
        break
      case '@tamarind/remove-item':
        this._handler9 = handler
        break
      case '@tamarind/remove-items':
        this._handler10 = handler
        break
      case '@tamarind/add-chat':
        this._handler11 = handler
        break
      default:
        throw DispatchError.NONEXISTENT_ROUTE(name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@tamarind/add-writer"')
    assert(this._handler1 !== null, 'Missing handler for "@tamarind/add-invite"')
    assert(this._handler2 !== null, 'Missing handler for "@tamarind/add-board"')
    assert(this._handler3 !== null, 'Missing handler for "@tamarind/rename-board"')
    assert(this._handler4 !== null, 'Missing handler for "@tamarind/delete-board"')
    assert(this._handler5 !== null, 'Missing handler for "@tamarind/add-item"')
    assert(this._handler6 !== null, 'Missing handler for "@tamarind/add-items"')
    assert(this._handler7 !== null, 'Missing handler for "@tamarind/update-item"')
    assert(this._handler8 !== null, 'Missing handler for "@tamarind/reorder"')
    assert(this._handler9 !== null, 'Missing handler for "@tamarind/remove-item"')
    assert(this._handler10 !== null, 'Missing handler for "@tamarind/remove-items"')
    assert(this._handler11 !== null, 'Missing handler for "@tamarind/add-chat"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      case 4:
        return this._handler4(op.value, context)
      case 5:
        return this._handler5(op.value, context)
      case 6:
        return this._handler6(op.value, context)
      case 7:
        return this._handler7(op.value, context)
      case 8:
        return this._handler8(op.value, context)
      case 9:
        return this._handler9(op.value, context)
      case 10:
        return this._handler10(op.value, context)
      case 11:
        return this._handler11(op.value, context)
      default:
        throw DispatchError.HANDLER_NOT_FOUND_BY_ID(op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@tamarind/add-writer',
  id: 0,
  enc: getEncoding('@tamarind/writer')
}

const route1 = {
  name: '@tamarind/add-invite',
  id: 1,
  enc: getEncoding('@tamarind/invite')
}

const route2 = {
  name: '@tamarind/add-board',
  id: 2,
  enc: getEncoding('@tamarind/board')
}

const route3 = {
  name: '@tamarind/rename-board',
  id: 3,
  enc: getEncoding('@tamarind/board-rename')
}

const route4 = {
  name: '@tamarind/delete-board',
  id: 4,
  enc: getEncoding('@tamarind/board-delete')
}

const route5 = {
  name: '@tamarind/add-item',
  id: 5,
  enc: getEncoding('@tamarind/item')
}

const route6 = {
  name: '@tamarind/add-items',
  id: 6,
  enc: getEncoding('@tamarind/item-batch')
}

const route7 = {
  name: '@tamarind/update-item',
  id: 7,
  enc: getEncoding('@tamarind/item-update')
}

const route8 = {
  name: '@tamarind/reorder',
  id: 8,
  enc: getEncoding('@tamarind/item-reorder')
}

const route9 = {
  name: '@tamarind/remove-item',
  id: 9,
  enc: getEncoding('@tamarind/item-remove')
}

const route10 = {
  name: '@tamarind/remove-items',
  id: 10,
  enc: getEncoding('@tamarind/items-remove')
}

const route11 = {
  name: '@tamarind/add-chat',
  id: 11,
  enc: getEncoding('@tamarind/chat-msg')
}

function getRouteByName (name) {
  switch (name) {
    case '@tamarind/add-writer':
      return route0
    case '@tamarind/add-invite':
      return route1
    case '@tamarind/add-board':
      return route2
    case '@tamarind/rename-board':
      return route3
    case '@tamarind/delete-board':
      return route4
    case '@tamarind/add-item':
      return route5
    case '@tamarind/add-items':
      return route6
    case '@tamarind/update-item':
      return route7
    case '@tamarind/reorder':
      return route8
    case '@tamarind/remove-item':
      return route9
    case '@tamarind/remove-items':
      return route10
    case '@tamarind/add-chat':
      return route11
    default:
      throw DispatchError.ROUTE_NOT_FOUND_BY_NAME(name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    case 4:
      return route4
    case 5:
      return route5
    case 6:
      return route6
    case 7:
      return route7
    case 8:
      return route8
    case 9:
      return route9
    case 10:
      return route10
    case 11:
      return route11
    default:
      throw DispatchError.HANDLER_NOT_FOUND_BY_ID(id)
  }
}

module.exports = {
  version,
  encode,
  decode,
  Router,
  DispatchError,
  ERRORS
}
