// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @tamarind/writer
const encoding0 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
  },
  encode(state, m) {
    c.buffer.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      key: r0
    }
  }
}

// @tamarind/invite
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @tamarind/board
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
    c.int.preencode(state, m.order)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
    c.int.encode(state, m.order)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const r3 = c.int.decode(state)
    const r4 = c.int.decode(state)

    return {
      id: r0,
      name: r1,
      createdAt: r2,
      updatedAt: r3,
      order: r4
    }
  }
}

// @tamarind/item
const encoding3 = {
  preencode(state, m) {
    const flags =
      (m.w ? 1 : 0) |
      (m.h ? 2 : 0) |
      (m.text ? 4 : 0) |
      (m.fill ? 8 : 0) |
      (m.lineCap ? 16 : 0) |
      (m.fontSize ? 32 : 0) |
      (m.start ? 64 : 0) |
      (m.end ? 128 : 0) |
      (m.arrowStart ? 256 : 0) |
      (m.arrowEnd ? 512 : 0) |
      (m.strokePattern ? 1024 : 0) |
      (m.curve ? 2048 : 0) |
      (m.label ? 4096 : 0)

    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.type)
    c.float64.preencode(state, m.x)
    c.float64.preencode(state, m.y)
    c.uint.preencode(state, flags)

    if (m.w) c.float64.preencode(state, m.w)
    if (m.h) c.float64.preencode(state, m.h)
    if (m.text) c.string.preencode(state, m.text)
    c.string.preencode(state, m.stroke)
    c.float64.preencode(state, m.strokeWidth)
    if (m.fill) c.string.preencode(state, m.fill)
    if (m.lineCap) c.string.preencode(state, m.lineCap)
    if (m.fontSize) c.float64.preencode(state, m.fontSize)
    if (m.start) c.string.preencode(state, m.start)
    if (m.end) c.string.preencode(state, m.end)
    if (m.arrowStart) c.string.preencode(state, m.arrowStart)
    if (m.arrowEnd) c.string.preencode(state, m.arrowEnd)
    if (m.strokePattern) c.string.preencode(state, m.strokePattern)
    if (m.curve) c.string.preencode(state, m.curve)
    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.order)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.w ? 1 : 0) |
      (m.h ? 2 : 0) |
      (m.text ? 4 : 0) |
      (m.fill ? 8 : 0) |
      (m.lineCap ? 16 : 0) |
      (m.fontSize ? 32 : 0) |
      (m.start ? 64 : 0) |
      (m.end ? 128 : 0) |
      (m.arrowStart ? 256 : 0) |
      (m.arrowEnd ? 512 : 0) |
      (m.strokePattern ? 1024 : 0) |
      (m.curve ? 2048 : 0) |
      (m.label ? 4096 : 0)

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.type)
    c.float64.encode(state, m.x)
    c.float64.encode(state, m.y)
    c.uint.encode(state, flags)

    if (m.w) c.float64.encode(state, m.w)
    if (m.h) c.float64.encode(state, m.h)
    if (m.text) c.string.encode(state, m.text)
    c.string.encode(state, m.stroke)
    c.float64.encode(state, m.strokeWidth)
    if (m.fill) c.string.encode(state, m.fill)
    if (m.lineCap) c.string.encode(state, m.lineCap)
    if (m.fontSize) c.float64.encode(state, m.fontSize)
    if (m.start) c.string.encode(state, m.start)
    if (m.end) c.string.encode(state, m.end)
    if (m.arrowStart) c.string.encode(state, m.arrowStart)
    if (m.arrowEnd) c.string.encode(state, m.arrowEnd)
    if (m.strokePattern) c.string.encode(state, m.strokePattern)
    if (m.curve) c.string.encode(state, m.curve)
    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.order)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.float64.decode(state)
    const r4 = c.float64.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      boardId: r1,
      type: r2,
      x: r3,
      y: r4,
      w: (flags & 1) !== 0 ? c.float64.decode(state) : 0,
      h: (flags & 2) !== 0 ? c.float64.decode(state) : 0,
      text: (flags & 4) !== 0 ? c.string.decode(state) : null,
      stroke: c.string.decode(state),
      strokeWidth: c.float64.decode(state),
      fill: (flags & 8) !== 0 ? c.string.decode(state) : null,
      lineCap: (flags & 16) !== 0 ? c.string.decode(state) : null,
      fontSize: (flags & 32) !== 0 ? c.float64.decode(state) : 0,
      start: (flags & 64) !== 0 ? c.string.decode(state) : null,
      end: (flags & 128) !== 0 ? c.string.decode(state) : null,
      arrowStart: (flags & 256) !== 0 ? c.string.decode(state) : null,
      arrowEnd: (flags & 512) !== 0 ? c.string.decode(state) : null,
      strokePattern: (flags & 1024) !== 0 ? c.string.decode(state) : null,
      curve: (flags & 2048) !== 0 ? c.string.decode(state) : null,
      label: (flags & 4096) !== 0 ? c.string.decode(state) : null,
      order: c.int.decode(state),
      updatedAt: c.int.decode(state)
    }
  }
}

// @tamarind/chat-msg
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.text)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @tamarind/board-rename
const encoding5 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.string.encode(state, m.name)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      name: r1,
      at: r2
    }
  }
}

// @tamarind/board-delete
const encoding6 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      id: r0
    }
  }
}

// @tamarind/item-batch
const encoding7 = {
  preencode(state, m) {
    c.json.preencode(state, m.items)
  },
  encode(state, m) {
    c.json.encode(state, m.items)
  },
  decode(state) {
    const r0 = c.json.decode(state)

    return {
      items: r0
    }
  }
}

// @tamarind/item-update
const encoding8 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.json.preencode(state, m.patch)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.json.encode(state, m.patch)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.json.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      patch: r1,
      at: r2
    }
  }
}

// @tamarind/item-reorder
const encoding9 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.int.preencode(state, m.order)
    c.int.preencode(state, m.at)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
    c.int.encode(state, m.order)
    c.int.encode(state, m.at)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.int.decode(state)
    const r2 = c.int.decode(state)

    return {
      id: r0,
      order: r1,
      at: r2
    }
  }
}

// @tamarind/item-remove
const encoding10 = encoding6

// @tamarind/items-remove
const encoding11 = {
  preencode(state, m) {
    c.json.preencode(state, m.ids)
  },
  encode(state, m) {
    c.json.encode(state, m.ids)
  },
  decode(state) {
    const r0 = c.json.decode(state)

    return {
      ids: r0
    }
  }
}

// @tamarind/chats-remove
const encoding12 = encoding11

// @tamarind/ai-state
const encoding13 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.writerKey)
    state.end++ // max flag is 8 so always one byte

    if (m.modelId) c.string.preencode(state, m.modelId)
    if (m.modelName) c.string.preencode(state, m.modelName)
    if (m.loadedAt) c.int.preencode(state, m.loadedAt)
  },
  encode(state, m) {
    const flags =
      (m.modelId ? 1 : 0) | (m.modelName ? 2 : 0) | (m.loadedAt ? 4 : 0) | (m.accepting ? 8 : 0)

    c.buffer.encode(state, m.writerKey)
    c.uint.encode(state, flags)

    if (m.modelId) c.string.encode(state, m.modelId)
    if (m.modelName) c.string.encode(state, m.modelName)
    if (m.loadedAt) c.int.encode(state, m.loadedAt)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      writerKey: r0,
      modelId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      modelName: (flags & 2) !== 0 ? c.string.decode(state) : null,
      loadedAt: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      accepting: (flags & 8) !== 0
    }
  }
}

// @tamarind/ai-state-update
const encoding14 = {
  preencode(state, m) {
    state.end++ // max flag is 16 so always one byte

    if (m._writerKey) c.string.preencode(state, m._writerKey)
    if (m.modelId) c.string.preencode(state, m.modelId)
    if (m.modelName) c.string.preencode(state, m.modelName)
    if (m.loadedAt) c.int.preencode(state, m.loadedAt)
  },
  encode(state, m) {
    const flags =
      (m._writerKey ? 1 : 0) |
      (m.modelId ? 2 : 0) |
      (m.modelName ? 4 : 0) |
      (m.loadedAt ? 8 : 0) |
      (m.accepting ? 16 : 0)

    c.uint.encode(state, flags)

    if (m._writerKey) c.string.encode(state, m._writerKey)
    if (m.modelId) c.string.encode(state, m.modelId)
    if (m.modelName) c.string.encode(state, m.modelName)
    if (m.loadedAt) c.int.encode(state, m.loadedAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      _writerKey: (flags & 1) !== 0 ? c.string.decode(state) : null,
      modelId: (flags & 2) !== 0 ? c.string.decode(state) : null,
      modelName: (flags & 4) !== 0 ? c.string.decode(state) : null,
      loadedAt: (flags & 8) !== 0 ? c.int.decode(state) : 0,
      accepting: (flags & 16) !== 0
    }
  }
}

// @tamarind/relay-request
const encoding15 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.json.preencode(state, m.messages)
    c.string.preencode(state, m.modelId)
    c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.json.encode(state, m.messages)
    c.string.encode(state, m.modelId)
    c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.json.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.int.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2,
      messages: r3,
      modelId: r4,
      createdAt: r5
    }
  }
}

// @tamarind/relay-response
const encoding16 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.string.preencode(state, m.kind)
    state.end++ // max flag is 2 so always one byte

    if (m.text) c.string.preencode(state, m.text)
    if (m.error) c.json.preencode(state, m.error)
  },
  encode(state, m) {
    const flags = (m.text ? 1 : 0) | (m.error ? 2 : 0)

    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.string.encode(state, m.kind)
    c.uint.encode(state, flags)

    if (m.text) c.string.encode(state, m.text)
    if (m.error) c.json.encode(state, m.error)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2,
      kind: r3,
      text: (flags & 1) !== 0 ? c.string.decode(state) : null,
      error: (flags & 2) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @tamarind/relay-cancel
const encoding17 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
  },
  encode(state, m) {
    c.string.encode(state, m.requestId)
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)

    return {
      requestId: r0,
      fromKey: r1,
      toKey: r2
    }
  }
}

// @tamarind/board/hyperdb#0
const encoding18 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
    c.int.preencode(state, m.order)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
    c.int.encode(state, m.order)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const r3 = c.int.decode(state)
    const r4 = c.int.decode(state)

    return {
      id: null,
      name: r1,
      createdAt: r2,
      updatedAt: r3,
      order: r4
    }
  }
}

// @tamarind/item/hyperdb#1
const encoding19 = {
  preencode(state, m) {
    const flags =
      (m.w ? 1 : 0) |
      (m.h ? 2 : 0) |
      (m.text ? 4 : 0) |
      (m.fill ? 8 : 0) |
      (m.lineCap ? 16 : 0) |
      (m.fontSize ? 32 : 0) |
      (m.start ? 64 : 0) |
      (m.end ? 128 : 0) |
      (m.arrowStart ? 256 : 0) |
      (m.arrowEnd ? 512 : 0) |
      (m.strokePattern ? 1024 : 0) |
      (m.curve ? 2048 : 0) |
      (m.label ? 4096 : 0)

    c.buffer.preencode(state, m.boardId)
    c.string.preencode(state, m.type)
    c.float64.preencode(state, m.x)
    c.float64.preencode(state, m.y)
    c.uint.preencode(state, flags)

    if (m.w) c.float64.preencode(state, m.w)
    if (m.h) c.float64.preencode(state, m.h)
    if (m.text) c.string.preencode(state, m.text)
    c.string.preencode(state, m.stroke)
    c.float64.preencode(state, m.strokeWidth)
    if (m.fill) c.string.preencode(state, m.fill)
    if (m.lineCap) c.string.preencode(state, m.lineCap)
    if (m.fontSize) c.float64.preencode(state, m.fontSize)
    if (m.start) c.string.preencode(state, m.start)
    if (m.end) c.string.preencode(state, m.end)
    if (m.arrowStart) c.string.preencode(state, m.arrowStart)
    if (m.arrowEnd) c.string.preencode(state, m.arrowEnd)
    if (m.strokePattern) c.string.preencode(state, m.strokePattern)
    if (m.curve) c.string.preencode(state, m.curve)
    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.order)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags =
      (m.w ? 1 : 0) |
      (m.h ? 2 : 0) |
      (m.text ? 4 : 0) |
      (m.fill ? 8 : 0) |
      (m.lineCap ? 16 : 0) |
      (m.fontSize ? 32 : 0) |
      (m.start ? 64 : 0) |
      (m.end ? 128 : 0) |
      (m.arrowStart ? 256 : 0) |
      (m.arrowEnd ? 512 : 0) |
      (m.strokePattern ? 1024 : 0) |
      (m.curve ? 2048 : 0) |
      (m.label ? 4096 : 0)

    c.buffer.encode(state, m.boardId)
    c.string.encode(state, m.type)
    c.float64.encode(state, m.x)
    c.float64.encode(state, m.y)
    c.uint.encode(state, flags)

    if (m.w) c.float64.encode(state, m.w)
    if (m.h) c.float64.encode(state, m.h)
    if (m.text) c.string.encode(state, m.text)
    c.string.encode(state, m.stroke)
    c.float64.encode(state, m.strokeWidth)
    if (m.fill) c.string.encode(state, m.fill)
    if (m.lineCap) c.string.encode(state, m.lineCap)
    if (m.fontSize) c.float64.encode(state, m.fontSize)
    if (m.start) c.string.encode(state, m.start)
    if (m.end) c.string.encode(state, m.end)
    if (m.arrowStart) c.string.encode(state, m.arrowStart)
    if (m.arrowEnd) c.string.encode(state, m.arrowEnd)
    if (m.strokePattern) c.string.encode(state, m.strokePattern)
    if (m.curve) c.string.encode(state, m.curve)
    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.order)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.float64.decode(state)
    const r4 = c.float64.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      boardId: r1,
      type: r2,
      x: r3,
      y: r4,
      w: (flags & 1) !== 0 ? c.float64.decode(state) : 0,
      h: (flags & 2) !== 0 ? c.float64.decode(state) : 0,
      text: (flags & 4) !== 0 ? c.string.decode(state) : null,
      stroke: c.string.decode(state),
      strokeWidth: c.float64.decode(state),
      fill: (flags & 8) !== 0 ? c.string.decode(state) : null,
      lineCap: (flags & 16) !== 0 ? c.string.decode(state) : null,
      fontSize: (flags & 32) !== 0 ? c.float64.decode(state) : 0,
      start: (flags & 64) !== 0 ? c.string.decode(state) : null,
      end: (flags & 128) !== 0 ? c.string.decode(state) : null,
      arrowStart: (flags & 256) !== 0 ? c.string.decode(state) : null,
      arrowEnd: (flags & 512) !== 0 ? c.string.decode(state) : null,
      strokePattern: (flags & 1024) !== 0 ? c.string.decode(state) : null,
      curve: (flags & 2048) !== 0 ? c.string.decode(state) : null,
      label: (flags & 4096) !== 0 ? c.string.decode(state) : null,
      order: c.int.decode(state),
      updatedAt: c.int.decode(state)
    }
  }
}

// @tamarind/chat-msg/hyperdb#2
const encoding20 = {
  preencode(state, m) {
    c.string.preencode(state, m.text)
    state.end++ // max flag is 1 so always one byte

    if (m.info) c.json.preencode(state, m.info)
  },
  encode(state, m) {
    const flags = m.info ? 1 : 0

    c.string.encode(state, m.text)
    c.uint.encode(state, flags)

    if (m.info) c.json.encode(state, m.info)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      text: r1,
      info: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @tamarind/invite/hyperdb#3
const encoding21 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.int.preencode(state, m.expires)
  },
  encode(state, m) {
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.int.encode(state, m.expires)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.int.decode(state)

    return {
      id: null,
      invite: r1,
      publicKey: r2,
      expires: r3
    }
  }
}

// @tamarind/ai-state/hyperdb#4
const encoding22 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.modelId) c.string.preencode(state, m.modelId)
    if (m.modelName) c.string.preencode(state, m.modelName)
    if (m.loadedAt) c.int.preencode(state, m.loadedAt)
  },
  encode(state, m) {
    const flags =
      (m.modelId ? 1 : 0) | (m.modelName ? 2 : 0) | (m.loadedAt ? 4 : 0) | (m.accepting ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.modelId) c.string.encode(state, m.modelId)
    if (m.modelName) c.string.encode(state, m.modelName)
    if (m.loadedAt) c.int.encode(state, m.loadedAt)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      writerKey: null,
      modelId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      modelName: (flags & 2) !== 0 ? c.string.decode(state) : null,
      loadedAt: (flags & 4) !== 0 ? c.int.decode(state) : 0,
      accepting: (flags & 8) !== 0
    }
  }
}

// @tamarind/relay-request/hyperdb#5
const encoding23 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
    c.json.preencode(state, m.messages)
    c.string.preencode(state, m.modelId)
    c.int.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
    c.json.encode(state, m.messages)
    c.string.encode(state, m.modelId)
    c.int.encode(state, m.createdAt)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.json.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.int.decode(state)

    return {
      requestId: null,
      fromKey: r1,
      toKey: r2,
      messages: r3,
      modelId: r4,
      createdAt: r5
    }
  }
}

// @tamarind/relay-response/hyperdb#6
const encoding24 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.toKey)
    c.string.preencode(state, m.kind)
    state.end++ // max flag is 2 so always one byte

    if (m.text) c.string.preencode(state, m.text)
    if (m.error) c.json.preencode(state, m.error)
  },
  encode(state, m) {
    const flags = (m.text ? 1 : 0) | (m.error ? 2 : 0)

    c.buffer.encode(state, m.toKey)
    c.string.encode(state, m.kind)
    c.uint.encode(state, flags)

    if (m.text) c.string.encode(state, m.text)
    if (m.error) c.json.encode(state, m.error)
  },
  decode(state) {
    const r2 = c.buffer.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      requestId: null,
      fromKey: null,
      toKey: r2,
      kind: r3,
      text: (flags & 1) !== 0 ? c.string.decode(state) : null,
      error: (flags & 2) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @tamarind/relay-cancel/hyperdb#7
const encoding25 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.fromKey)
    c.buffer.preencode(state, m.toKey)
  },
  encode(state, m) {
    c.buffer.encode(state, m.fromKey)
    c.buffer.encode(state, m.toKey)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)

    return {
      requestId: null,
      fromKey: r1,
      toKey: r2
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@tamarind/writer':
      return encoding0
    case '@tamarind/invite':
      return encoding1
    case '@tamarind/board':
      return encoding2
    case '@tamarind/item':
      return encoding3
    case '@tamarind/chat-msg':
      return encoding4
    case '@tamarind/board-rename':
      return encoding5
    case '@tamarind/board-delete':
      return encoding6
    case '@tamarind/item-batch':
      return encoding7
    case '@tamarind/item-update':
      return encoding8
    case '@tamarind/item-reorder':
      return encoding9
    case '@tamarind/item-remove':
      return encoding10
    case '@tamarind/items-remove':
      return encoding11
    case '@tamarind/chats-remove':
      return encoding12
    case '@tamarind/ai-state':
      return encoding13
    case '@tamarind/ai-state-update':
      return encoding14
    case '@tamarind/relay-request':
      return encoding15
    case '@tamarind/relay-response':
      return encoding16
    case '@tamarind/relay-cancel':
      return encoding17
    case '@tamarind/board/hyperdb#0':
      return encoding18
    case '@tamarind/item/hyperdb#1':
      return encoding19
    case '@tamarind/chat-msg/hyperdb#2':
      return encoding20
    case '@tamarind/invite/hyperdb#3':
      return encoding21
    case '@tamarind/ai-state/hyperdb#4':
      return encoding22
    case '@tamarind/relay-request/hyperdb#5':
      return encoding23
    case '@tamarind/relay-response/hyperdb#6':
      return encoding24
    case '@tamarind/relay-cancel/hyperdb#7':
      return encoding25
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
